### ISSUE TITLE
License

### ISSUE THREAD

**Issue by vmario89** [miffysora/Inkscape#1]
Hi,

found this repo and started to migrate a lot of things to InkScape 1.0

i wanted you to ask if you could add some license like MIT or GPL because it's not that open at the moment without a license.

regards, Mario ;-)

**Comment by miffysora** [comment]
Thanks! I added a license MIT by this commit ->https://github.com/miffysora/Inkscape/commit/8a0f4a244e14e78901dd36c993429c5f0e15dec6
